//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablo
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public Nullable<double> Ucret { get; set; }
    }
}
